<?php


namespace App\Repositories;


use App\Models\Expense;
use App\Models\Payment;
use App\Repositories\Contracts\ExpenseRepository;
use App\Repositories\Contracts\PaymentRepository;
use Carbon\Carbon;
use Illuminate\Validation\ValidationException;

class EloquentExpenseRepository extends EloquentBaseRepository implements ExpenseRepository
{
    /**
     * @inheritdoc
     */
    public function findBy(array $searchCriteria = [], $withTrashed = false)
    {
        $queryBuilder = $this->model;

        if (isset($searchCriteria['endDate'])) {
            $queryBuilder  =  $queryBuilder->whereDate('created_at', '<=', Carbon::parse($searchCriteria['endDate']));
            unset($searchCriteria['endDate']);
        }

        if (isset($searchCriteria['startDate'])) {
            $queryBuilder =  $queryBuilder->whereDate('created_at', '>=', Carbon::parse($searchCriteria['startDate']));
            unset($searchCriteria['startDate']);
        }

        if (isset($searchCriteria['query'])) {
            $searchCriteria['id'] = $this->model->where('expenseReason', 'like', '%' . $searchCriteria['query'] . '%')
                ->orWhereHas('category', function($query) use ($searchCriteria){
                    $query->where('name', 'like', '%' . $searchCriteria['query'] . '%');
                })
                ->pluck('id')->toArray();
            unset($searchCriteria['query']);
        }

        $withSummary = false;
        if (!empty($searchCriteria['withSummary'])) {
            unset($searchCriteria['withSummary']);
            $withSummary = true;
        }

        $queryBuilder = $queryBuilder->where(function ($query) use ($searchCriteria) {
            $this->applySearchCriteriaInQueryBuilder($query, $searchCriteria);
        });

        $limit = !empty($searchCriteria['per_page']) ? (int)$searchCriteria['per_page'] : 15;
        $orderBy = !empty($searchCriteria['order_by']) ? $searchCriteria['order_by'] : 'id';
        $orderDirection = !empty($searchCriteria['order_direction']) ? $searchCriteria['order_direction'] : 'desc';
        $queryBuilder->orderBy($orderBy, $orderDirection);

        $summary = [];
        if ($withSummary) {
            $allData = $queryBuilder->get();
            $summary['numberOfCategory'] = $allData->unique('categoryId')->count();
            $summary['totalExpense'] = $allData->sum('amount');
        }

        if (empty($searchCriteria['withoutPagination'])) {
            $expenses = $queryBuilder->paginate($limit);
        } else {
            $expenses = $queryBuilder->get();
        }


        $pageWiseSummary = [];

        $pageWiseSummary['numberOfCategory'] = $expenses->unique('categoryId')->count();
        $pageWiseSummary['totalExpense'] = $expenses->sum('amount');

        if ($withSummary){
            return ['expenses' => $expenses, 'summary' => $summary, 'pageWiseSummary' => $pageWiseSummary];
        }

        return ['expenses' => $expenses, 'pageWiseSummary' => $pageWiseSummary];
    }

    /**
     * @inheritdoc
     */
    public function save(array $data): \ArrayAccess
    {
        $expense = parent::save($data);

        $paymentData['status'] = Payment::STATUS_SUCCESS;
        $paymentData['cashFlow'] = Payment::CASH_FLOW_OUT;
        $paymentData['paymentableId'] = $expense->id;
        $paymentData['paymentableType'] = Payment::PAYMENT_SOURCE_EXPENSE;
        $paymentData['payType'] = Payment::PAY_TYPE_EXPENSE;
        $paymentData['receivedByUserId'] = $expense->createdByUserId;
        $paymentData['date'] = Carbon::now();
        $paymentData['amount'] = $expense->amount;
        $paymentData['method'] = Payment::METHOD_CASH;
        $paymentRepository = app(PaymentRepository::class);
        $paymentRepository->save($paymentData);

        return  $expense;
    }

    /**
     * @inheritdoc
     */
    public function update(\ArrayAccess $model, array $data): \ArrayAccess
    {
        $expense = parent::update($model, $data); // TODO: Change the autogenerated stub

        $paymentRepository = app(PaymentRepository::class);

        $payment = $paymentRepository->findOneBy([
            'paymentableId' => $expense->id,
            'paymentableType' => Expense::class,
            'payType' => Payment::PAY_TYPE_EXPENSE,
        ]);

        if($payment instanceof Payment) {
            $paymentData['amount'] = $expense->amount;

            $paymentRepository->update($payment, $paymentData);
        }

        return  $expense;
    }

}
